stages:
  - build
  - test
  - deploy

Install Dependencies:
  image: node:alpine3.15
  stage: build
  before_script:
    - apk update
    - apk upgrade
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

# Execute Tests:
#   image: node:alpine3.15
#   stage: test
#   script:
#     - npm run test

Deliver app (Pre production):
  image: ruby:2.3-slim
  stage: deploy
  only:
    refs:
      - staging
  before_script:
    - apt-get update -qy
    - apt-get install -y make gcc curl git
  script:
    - gem install dpl --pre
    - dpl --provider=heroku --app=fecit-api-staging --api_key=$HEROKU_API_KEY

Deliver app (Production):
  image: ruby:2.3-slim
  stage: deploy
  only:
    refs:
      - main
  before_script:
    - apt-get update -qy
    - apt-get install -y make gcc curl git
  script:
    - gem install dpl
    - dpl --provider=heroku --app=fecit-api-staging --api_key=$HEROKU_API_KEY
