stages:
  - build
  - test
  - deploy

Install Dependencies:
  image: nginx:stable
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

Execute Tests:
  image: node:alpine3.15
  state: test
  script:
    - npm run test

Deliver app (Pre production):
  image: ruby:2.3-slim
  stage: deloy
  only:
    refs:
      - staging
  before_scripts:
    - apt-get update -qy
    - apt-get install -y make gcc curl git
  script:
    - gem install dpl --pre
    - dpl heroku api --api_key $HEROKU_API_KEY --app fecit-webapp-staging

Deliver app (Production):
  image: ruby:2.3-slim
  stage: deloy
  only:
    refs:
      - master
  before_scripts:
    - apt-get update -qy
    - apt-get install -y make gcc curl git
  script:
    - gem install dpl --pre
    - dpl heroku api --api_key $HEROKU_API_KEY --app fecit-webapp-staging
