@url = http://localhost:3977/api/v1
@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYyMmZkMjA4NzE5YjU0NjM4YTY5ZDVjNSIsImVtYWlsIjoiaWRldmtpbmdvc0BnbWFpbC5jb20iLCJpYXQiOjE2NDc5OTMwNjIsImV4cCI6MTY0ODAwMzg2Mn0.zMP4RQxtr0N0kBlPxHysnTin9MiP8bIkQ1Wec6tIH_Y

### Signup
POST {{url}}/signup
Content-Type: application/json

{
  "name": "Joaquin",
  "lastname": "Valdes",
  "email": "joaquin@gmail.com",
  "password": "123456",
  "confirmPassword": "123456",
  "roles": ["ADMIN"],
  "agreement": true
}
### List of users

GET {{url}}/users?active=true
Content-Type: application/json
Authorization: Bearer {{accessToken}}
