@url = http://localhost:3977/api/v1
@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYyMmZkMjA4NzE5YjU0NjM4YTY5ZDVjNSIsImVtYWlsIjoiaWRldmtpbmdvc0BnbWFpbC5jb20iLCJpYXQiOjE2NTA0NjgwMzgsImV4cCI6MTY1MDQ3ODgzOH0.GX0LlILLlDiUaCNyv1KFyvjh9evVe_OpUUl-V7UUszA

### Signup
POST {{url}}/signup
Content-Type: application/json

{
  "name": "Joaquin",
  "lastname": "Valdes",
  "email": "joaquin@gmail.com",
  "password": "123456",
  "confirmPassword": "123456",
  "roles": ["ADMIN"],
  "agreement": true
}
### Update user
PUT {{url}}/users/6237d16f8b2754d26a029b47
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Joaquín",
  "lastname": "Valdés"
}

### List of users
GET {{url}}/users?active=true
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Upload avatar
PUT {{url}}/upload/avatar/622fd208719b54638a69d5c5
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="javascript.jpg"
Content-Type: image/jpg

< ./javascript.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
